Description: Infrastructure for the ECR repositories
Resources:
  PythonRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: python-codebuild-image
      LifecyclePolicy:
        LifecyclePolicyText: >
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Statement:
          -
            Sid: CodeBuildAccess
            Principal:
              Service:
                - codebuild.amazonaws.com
              AWS: !ImportValue core-infrastructure-codebuild-base-role-arn
              Action:
                - ecr:GetDownloadUrlForLayer
                - ecr:BatchGetImage
                - ecr:BatchCheckLayerAvailability
      # RepositoryPolicyText: >
      #   {
      #     "Statement": [
      #       {
      #         "Sid": "CodeBuildAccess",
      #         "Effect": "Allow",
      #         "Principal": {
      #           "Service": [
      #             "codebuild.amazonaws.com"
      #           ],
      #           "AWS": {
      #             "Fn::ImportValue": "core-infrastructure-codebuild-base-role-arn"
      #           }
      #         },
      #         "Action": [
      #           "ecr:GetDownloadUrlForLayer",
      #           "ecr:BatchGetImage",
      #           "ecr:BatchCheckLayerAvailability"
      #         ]
      #       }
      #     ]
      #   }
