Description: Infrastructure for the ECR repositories
Parameters:
  BasePolicyArn:
    Type: String
    Description: IAM Policy ARN of the base CodeBuild policy
    Default: arn:aws:iam::008356366354:policy/core-infrastructure-CodeBuildBaseManagedPolicy-19Z49JKLYIPMS
Outputs:
  PythonRepositoryName:
    Description: Name of the ECR repository for the Python 2.7 image
    Value: !Ref PythonRepository
    Export:
      Name: !Sub '${AWS::StackName}-python-repository-name'
Resources:
  PythonRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: python27-codebuild-image
      LifecyclePolicy:
        LifecyclePolicyText: >
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Statement:
          -
            Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
              AWS: !Ref BasePolicyArn
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
