Description: Infrastructure for the ECR repositories
Parameters:
  BaseRoleArn:
    Type: String
    Description: IAM Role ARN of the base CodeBuild role
    Default: arn:aws:iam::008356366354:role/core-infrastructure-globa-CodeBuildBaseRole82AEF9B-16WTO0UXBZ619
Outputs:
  PythonRepositoryName:
    Description: Name of the ECR repository for the Python 2.7 image
    Value: !Ref PythonRepository
    Export:
      Name: !Sub '${AWS::StackName}-python-repository-name'
Resources:
  PythonRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: python27-codebuild-image
      LifecyclePolicy:
        LifecyclePolicyText: >
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Statement:
          -
            Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
              AWS: !Ref BaseRoleArn
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
  CentOS7Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: centos7-codebuild-image
      LifecyclePolicy:
        LifecyclePolicyText: >
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire untagged images after 1 day",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      RepositoryPolicyText:
        Statement:
          -
            Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
              AWS: !Ref BaseRoleArn
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
