Description: Pipeline for my CodeBuild images
Parameters:
  BasePolicyArn:
    Type: String
    Description: IAM Policy ARN of the base CodeBuild policy
    Default: arn:aws:iam::008356366354:policy/core-infrastructure-global-CodeBuildBaseManagedPolicy-FWV7ZO5N6AGF
  CodePipelineCloudFormationRoleArn:
    Type: String
    Description: IAM Role ARN to be assumed by CodePipeline to perform CloudFormation actions
    Default: arn:aws:iam::008356366354:role/core-infrastructure-globa-CodePipelineCloudFormati-1NF00Q6M6OVE1
  BuildArtifactsBucketName:
    Type: String
    Description: S3 Bucket name where build artifacts are stored
    Default: core-infrastructure-eu-w-buildartifactsbucketeuwe-12d2acmozch84
  CodePipelineExecutionRoleArn:
    Type: String
    Description: IAM Role ARN to be assumed by CodePipeline when executing
    Default: arn:aws:iam::008356366354:role/core-infrastructure-globa-CodePipelineBaseRoleB458-161XPXE39XXUL
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Ref BasePolicyArn
      Policies:
        - PolicyName: codebuild-images-role
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: ecr:*
                Resource: "*"

  Python27CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref BuildArtifactsBucketName
        Path: /artifacts/codebuild-images/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds Python 2.7 CodeBuild image
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: IMAGE
            Value: python2.7
            Type: PLAINTEXT
          - Name: REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          - Name: TARGET_IMAGE
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/python27-codebuild-image:latest"
            Type: PLAINTEXT
      Name: codebuild-images-python27
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CentOS7CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref BuildArtifactsBucketName
        Path: /artifacts/codebuild-images/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds CentOS 7 CodeBuild image
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: IMAGE
            Value: centos7
            Type: PLAINTEXT
          - Name: REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          - Name: TARGET_IMAGE
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/centos7-codebuild-image:latest"
            Type: PLAINTEXT
      Name: codebuild-images-centos7
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  AmazonLinux2CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !Ref BuildArtifactsBucketName
        Path: /artifacts/codebuild-images/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds Amazon Linux 2 CodeBuild image
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: IMAGE
            Value: amazonlinux2
            Type: PLAINTEXT
          - Name: REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          - Name: TARGET_IMAGE
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/amazonlinux2-codebuild-image:latest"
            Type: PLAINTEXT
      Name: codebuild-images-amazonlinux2
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref BuildArtifactsBucketName
      Name: codebuild-images
      RestartExecutionOnUpdate: true
      RoleArn: !Ref CodePipelineExecutionRoleArn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Configuration:
                Owner: AlexChesters
                Repo: codebuild-images
                Branch: master
                OAuthToken: "{{resolve:ssm:/Secrets/GitHub-Token:1}}"
                PollForSourceChanges: false
        - Name: Deploy-CloudFormation
          Actions:
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Create-Change-Set
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: codebuild-repositories
                ChangeSetName: codebuild-repositories-change-set
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
                TemplatePath: GitHubSource::stacks/repositories.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/repositories.json
            - ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              RunOrder: 2
              Name: Run-Change-Set
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: codebuild-repositories
                ChangeSetName: codebuild-repositories-change-set
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
        - Name: Build-Images
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 3
              Name: Build-Python27-Image
              Configuration:
                ProjectName: !Ref "Python27CodeBuildProject"
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 3
              Name: Build-CentOS7-Image
              Configuration:
                ProjectName: !Ref "CentOS7CodeBuildProject"
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 3
              Name: Build-Amazon-Linux-2-Image
              Configuration:
                ProjectName: !Ref "AmazonLinux2CodeBuildProject"

  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:ssm:/Secrets/GitHub-Webhook-Secret:1}}"
      Filters:
        - JsonPath: "$.ref"
      TargetPipeline: !Ref CodePipeline
      TargetAction: Clone-From-GitHub
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true
