Description: Pipeline for my CodeBuild images
Parameters:
  BasePolicyArn:
    Type: String
    Description: IAM Policy ARN of the base CodeBuild policy
    Default: arn:aws:iam::008356366354:policy/core-infrastructure-CodeBuildBaseManagedPolicy-19Z49JKLYIPMS
  CodePipelineCloudFormationRoleArn:
    Type: String
    Description: IAM Role ARN to be assumed by CodePipeline to perform CloudFormation actions
    Default: arn:aws:iam::008356366354:role/core-infrastructure-CodePipelineCloudFormationRole-1MF3TS7NGYGJF
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - !Ref BasePolicyArn
      Policies:
        -
          PolicyName: codebuild-images-role
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: ecr:*
                Resource: '*'

  Python27CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
        Location: !ImportValue core-infrastructure-build-artifacts-bucket
        Path: /artifacts/codebuild-images/
        Packaging: NONE
        Name: build
        NamespaceType: BUILD_ID
      TimeoutInMinutes: 5
      Description: Builds and deploys my personal website to test
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          -
            Name: IMAGE
            Value: python2.7
            Type: PLAINTEXT
          -
            Name: REGION
            Value: !Ref AWS::Region
            Type: PLAINTEXT
          -
            Name: TARGET_IMAGE
            Value: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/python27-codebuild-image:latest'
            Type: PLAINTEXT
      Name: codebuild-images-python27
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !ImportValue core-infrastructure-build-artifacts-bucket
      Name: codebuild-images
      RestartExecutionOnUpdate: true
      RoleArn: !ImportValue core-infrastructure-codepipeline-base-role-arn
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: "1"
                Provider: GitHub
              OutputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Clone-From-GitHub
              Configuration:
                Owner: AlexChesters
                Repo: codebuild-images
                Branch: master
                OAuthToken: "{{resolve:ssm:/Secrets/GitHub-Token:1}}"
                PollForSourceChanges: false
        -
          Name: Deploy-CloudFormation
          Actions:
            -
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              InputArtifacts:
                - Name: GitHubSource
              RunOrder: 1
              Name: Create-Python27-Change-Set
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: codebuild-repositories
                ChangeSetName: codebuild-repositories-change-set
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
                TemplatePath: GitHubSource::stacks/repositories.yml
                TemplateConfiguration: GitHubSource::stacks/parameters/repositories.json
            -
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              RunOrder: 2
              Name: Run-Python27-Change-Set
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: codebuild-repositories
                ChangeSetName: codebuild-repositories-change-set
                RoleArn: !Ref CodePipelineCloudFormationRoleArn
        - Name: Build-Images
          Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: GitHubSource
              OutputArtifacts:
                - Name: BuildSource
              RunOrder: 3
              Name: Build-Python27-Image
              Configuration:
                ProjectName: !Ref "Python27CodeBuildProject"

  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: "{{resolve:ssm:/Secrets/GitHub-Webhook-Secret:1}}"
      Filters:
        - JsonPath: "$.ref"
      TargetPipeline: !Ref CodePipeline
      TargetAction: Clone-From-GitHub
      TargetPipelineVersion: !GetAtt CodePipeline.Version
      RegisterWithThirdParty: true
